version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: >-
    msbuild /t:restore

    cd Tests/MQTTnet.TestApp.AspNetCore2/

    npm install

build:
  project: MQTTnet.sln
  verbosity: minimal
test_script:
- cmd: vstest.console /logger:Appveyor Tests\MQTTnet.Core.Tests\bin\Release\netcoreapp2.0\MQTTnet.Core.Tests.dll
