version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: >-
    msbuild /t:restore MQTTnet.sln

    cd Tests/MQTTnet.TestApp.AspNetCore2/

    npm install

build:
  project: MQTTnet.sln
  verbosity: minimal
